api:
  prefix: /api/v1

spring:
  application:
    name: GIG
  datasource:
    url: jdbc:postgresql://localhost:5432/gig
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: youractual.address@gmail.com
    password: xxxxx xxxxx xxxxx # Replace with your actual password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        transport:
          protocol: smtp

telegram:
  bot:
    token: xxxxx xxxxx xxxxx # Replace with your actual bot token

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs
    enabled: true

auth:
  token:
    expirationInMils: 72000000
    jwtSecret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D